language: smalltalk
sudo: false

os:
  - linux
  - osx

smalltalk:
  - Squeak-5.2
  - Squeak-5.1

jobs:
  include:
    - stage: shortstage
      smalltalk_config: .smalltalk.ston
    - stage: longstage
      smalltalk_config: .smalltalk.ston
